//Requirement: based on number generated by Math.random, print distinctioln, pass, fail, second using ternary

package com.k2js.aboutconditions.practise;

class MarksTerenaryGood{
	
	static String marksTerenaryGood(int marks){
		String result = (marks>=75)?"Distinction":(marks>=60)?"First Class":(marks>=50)?"Second Class":(marks>=35)?"Pass":"Fail";
		return result;
	}
}

class MarksTerenaryGoodTest{
	
	public static void main(String...xxyy){
		int marks=(int)(Math.random()*90+10);
		String result = MarksTerenaryGood.marksTerenaryGood(marks);
		System.out.println(result +" : "+marks);
	}
}