//Requirement: based on number generated by Math.random, print distinctioln, pass, fail, second

package com.k2js.aboutconditions.practise;

class MarksIfElseGood{
	
	static String marksIfElseGood(int marks){
		String result=null;
		if(marks >= 75)
			result= "Distinction";
		else if(marks >= 60)
			result= "First class";
		else if(marks >= 50)
			result = "Second class"
		else if(marks >= 35)
			result = "Pass";
		else
			result = "Fail";
		
		return result;
	}
}

class MarksIfElseGoodTest{
	
	public static void main(String...xxyy){
		int marks=(int)(Math.random()*90+10);
		String result = MarksIfElseGood.marksIfElseGood(marks);
		System.out.println(result +" : "+marks);
	}
}